### ISSUE TITLE
Enemy zerg eggs/larva [reproduce?]

### ISSUE THREAD

**Issue by Venorcis** [eishub/Starcraft#71]
Sometimes the team's own zerg eggs (or larva?) are perceived as enemies

**Comment by Venorcis** [comment]
Probably deep down in JNIBWAPI/BWAPI, the units can never be both friendly and enemy by design. Perhaps comment as a known bug? And was it eggs or larvae or both?

**Comment by HarmGriffioen** [comment]
I agree with that solution

**Comment by Venorcis** [comment]
Let's close this, would be in BWAPI itself anyway
