### ISSUE TITLE
Conditions [manual]

### ISSUE THREAD

**Issue by Venorcis** [eishub/Starcraft#72]
It's not clear which conditions can be seen of enemies

**Comment by Venorcis** [comment]
I added conditions: defenseMatrixed, nukeReady, patrolling, burrowed, beingHealed, underAttack, repairing
This needs to be updated in the manual (+attacking and maybe some others too?)

**Comment by Venorcis** [comment]
I also got reports that beingConstructed is listed as isBeingConstructed in the manual

**Comment by Dahny** [comment]
Done, isbeingConstructed was old friendly percept -> removed and changed to beingConstructed.
Also added all the the new conditions to the manual.
