### ISSUE TITLE
Construction sites

### ISSUE THREAD

**Issue by Venorcis** [eishub/Starcraft#80]
Currently we have a 3x3 grid but we check if a 4x3 building can be built there (c.center/nexus/hatchery). If a building is on a 3x3 grid immediately to the right of an empty grid, that empty one will disappear anyone (because we check 4x3). Moreover, a main building has a larger minimum resource distance than others, thus removing a lot of potential construction sites for non-main buildings near minerals/geysers.

However, on the other hand, you do need to know if you can build a nexus somewhere or not; right now you can at all construction sites. Any changes here would be severely backward-compatibility breaking, and people cán try to build at places by just calling the build action and seeing if that work (i.e. a friendly percept appear or the building agent sends hello).

**Comment by Dahny** [comment]
Updated the manual with this information

**Comment by Venorcis** [comment]
Perhaps we can still think of a better system using BWMirror and BWTA2

**Comment by Venorcis** [comment]
In the newpercepts branch there is now a 2x2 grid on which only 2x2 buildings are checked. We still need to do some performance evaluations on this though
